---
# tasks file for roles/redis
- name: install redis
  apt:
    name: "{{ redis_packages }}"
    state: present
  register: redis_install_redis

- name: configure redis
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_configuration_directory }}/{{ redis_configuration_file }}"
    owner: "{{ redis_owner }}"
    group: "{{ redis_group }}"
    mode: "{{ redis_mode }}"
  notify:
    - restart redis
