---
- name: Install Redis packages
  package:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: latest
    install_recommends: no
  become: yes
  with_items:
      - redis-server
      - redis-tools
