---
# handlers file for roles/postfix
- name: restart postfix
  service:
    name: "{{ postfix_service }}"
    state: restarted

- name: rebuild alias database
  command: postmap "{{ postfix_alias_path }}"
