---
- name: create mastodon live site directory
  file:
      path: "{{ install_dir }}"
      state: directory
      owner: "{{ mastodon_user }}"
      group: "{{ mastodon_user }}"
  become: yes

- name: clone the repo
  git:
      repo: "https://github.com/tootsuite/mastodon.git"
      dest: "{{ install_dir }}"
      update: yes
      accept_hostkey: true
  become: yes
  become_user: "{{ mastodon_user }}"

- name: install bundler
  command: /usr/local/rbenv/shims/gem install bundler
  become: yes

- name: use bundler to install dependencies
  command: /usr/local/rbenv/shims/bundle install --deployment --without development test
  args:
    chdir: "{{ install_dir }}"
  become: yes
  become_user: "{{ mastodon_user }}"

- name: use yarn to install node dependencies
  command: yarn install --pure-lockfile
  args:
    chdir: "{{ install_dir }}"
  become: yes
  become_user: "{{ mastodon_user }}"
