---
- name: create mastodon live site directory
  file:
      path: "{{ mastodon_home }}/live"
      state: directory
      owner: "{{ mastodon_user }}"
      group: "{{ mastodon_user }}"

- name: clone the repo
  git:
      repo: "https://github.com/tootsuite/mastodon.git"
      dest: "{{ mastodon_home }}/live"
  become: "{{ mastodon_user }}"

- name: get latest stable branch
