---
# defaults file for roles/nginx
# The tcp port nginx should listen on.
# account_private_key: '/path/to/sample_com_private.key'
nginx_port: 80
nginx__upstream_repository: 'deb https://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} main'
