---
# tasks file for roles/mastodon_app
- name: create mastodon live site directory
  file:
      path: "{{ install_dir }}"
      state: directory
      owner: "mastodon"
      group: "mastodon"
  become: true

- name: clone the repo
  git:
      repo: "https://github.com/tootsuite/mastodon.git"
      dest: "{{ install_dir }}"
      update: yes
      accept_hostkey: true
  become: true

- name: use bundler to install dependencies
  command: bundle install --deployment --without development test
  args:
    chdir: "{{ install_dir }}"
  become: true
  become_user: "mastodon"

- name: use yarn to install node dependencies
  command: yarn install --pure-lockfile
  args:
    chdir: "{{ install_dir }}"
  become: true
  become_user: "mastodon"

- name: copy mastodon systemd webservice
  template:
    src: 'mastodon-web.service.j2'
    dest: '/etc/systemd/system/mastodon-web.service'
    owner: root
    group: root
  become: true

- name: copy mastodon systemd sidekiq service
  template:
    src: 'mastodon-sidekiq.service.j2'
    dest: '/etc/systemd/system/mastodon-sidekiq.service'
    owner: root
    group: root
  become: true

- name: copy mastodon systemd streaming service
  template:
    src: 'mastodon-streaming.service.j2'
    dest: '/etc/systemd/system/mastodon-streaming.service'
    owner: root
    group: root
  become: true
