---
galaxy_info:
  role_name: rvm
  author: kayiwa
  description: Role to install rvm
  company: huh

  license: MIT

  min_ansible_version: 2.7.11

  platforms:
    - name: Ubuntu
      versions:
        - 18.04
dependencies:
  - role: 'system_packages'
  - role: 'mastodon_user'
