---
# vars file for roles/system_packages
mastodon_system_packages:
  - imagemagick
  - python-apt
  - ffmpeg
  - libxml2-dev
  - libxslt1-dev
  - file
  - git-core
  - g++
  - libprotobuf-dev
  - protobuf-compiler
  - pkg-config
  - gcc
  - autoconf
  - bison
  - build-essential
  - libssl-dev
  - libyaml-dev
  - libreadline6-dev
  - zlib1g-dev
  - libncurses5-dev
  - libffi-dev
  - libgdbm5
  - libgdbm-dev
  - libidn11-dev
  - libicu-dev
  - libjemalloc-dev
  - curl
