---
# defaults file for roles/postgresql
postgres_settings:
  - name: listen_addresses
    value: 5432
  - name: max_wal_size
    value: 1GB
  - name: min_wal_size
    value: 80MB
  - name: log_timezone
    value: UCT
  - name: datestyle
    value: "'iso, ymd'"
  - name: timezone
    value: UCT
  - name: default_text_search_config
    value: "'pg_catalog.english'"
